//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WriteErase.DataBase
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Windows.Media;

    public partial class Product
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Product()
        {
            this.OrderProduct = new HashSet<OrderProduct>();
        }
    
        public string ProductArticleNumber { get; set; }
        public string ProductName { get; set; }
        public int UnitID { get; set; }
        public decimal ProductCost { get; set; }
        public Nullable<byte> ProductDiscountAmount { get; set; }
        public int ProductManufacturerID { get; set; }
        public int ProductSupplierID { get; set; }
        public int ProductCategory { get; set; }
        public decimal ProductCostWithDiscount
        {
            get
            {
                if (ProductActualDiscount != null)
                {
                    double discountSize = Convert.ToDouble(ProductActualDiscount) / 100;
                    decimal actualPrice = ProductCost - ProductCost * Convert.ToDecimal(discountSize);
                    return actualPrice;
                }

                else return 0;
            }
            set
            {
            }
        }
        public Nullable<byte> ProductActualDiscount { get; set; }
        public int ProductQuantityInStock { get; set; }
        public string ProductDescription { get; set; }
        public string ProductPhoto { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderProduct> OrderProduct { get; set; }
        public virtual ProductCategory ProductCategory1 { get; set; }
        public virtual ProductManufacturer ProductManufacturer { get; set; }
        public virtual ProductSupplier ProductSupplier { get; set; }
        public virtual Unit Unit { get; set; }
        public SolidColorBrush DiscountColor
        {
            get
            {
                if (ProductActualDiscount > 15)
                {
                    SolidColorBrush withDis = new SolidColorBrush(Color.FromRgb(127, 255, 0));
                    return withDis;
                }
                else
                {
                    SolidColorBrush withoutDis = new SolidColorBrush(Color.FromRgb(255, 255, 255));
                    return withoutDis;
                }
            }
        }

        public virtual string Count
        {
            get
            {
                List<DataBase.OrderProduct> listOrderProduct = Classes.Base.EM.OrderProduct.Where(x => x.OrderID == 54).ToList();
                DataBase.OrderProduct orderProduct = listOrderProduct.FirstOrDefault(x => x.ProductArticleNumber == ProductArticleNumber);

                return Convert.ToString(orderProduct.OrderCount);
            }
        }
    }
}

